/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_MotorGrafico */

#ifndef _Included_main_MotorGrafico
#define _Included_main_MotorGrafico
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_MotorGrafico
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_MotorGrafico_init
  (JNIEnv *, jobject);

/*
 * Class:     main_MotorGrafico
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_MotorGrafico_cleanup
  (JNIEnv *, jobject);

/*
 * Class:     main_MotorGrafico
 * Method:    isRunning
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_main_MotorGrafico_isRunning
  (JNIEnv *, jobject);

/*
 * Class:     main_MotorGrafico
 * Method:    setAlgorithm
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_main_MotorGrafico_setAlgorithm
  (JNIEnv *, jobject, jint);

/*
 * Class:     main_MotorGrafico
 * Method:    setDistribution
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_main_MotorGrafico_setDistribution
  (JNIEnv *, jobject, jint);

/*
 * Class:     main_MotorGrafico
 * Method:    setRenderMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_main_MotorGrafico_setRenderMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     main_MotorGrafico
 * Method:    setArraySize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_main_MotorGrafico_setArraySize
  (JNIEnv *, jobject, jint);

/*
 * Class:     main_MotorGrafico
 * Method:    setTickRate
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_main_MotorGrafico_setTickRate
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     main_MotorGrafico
 * Method:    toggleSorting
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_MotorGrafico_toggleSorting
  (JNIEnv *, jobject);

/*
 * Class:     main_MotorGrafico
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_MotorGrafico_reset
  (JNIEnv *, jobject);

/*
 * Class:     main_MotorGrafico
 * Method:    getComparisons
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_main_MotorGrafico_getComparisons
  (JNIEnv *, jobject);

/*
 * Class:     main_MotorGrafico
 * Method:    getWrites
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_main_MotorGrafico_getWrites
  (JNIEnv *, jobject);

/*
 * Class:     main_MotorGrafico
 * Method:    isSorting
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_main_MotorGrafico_isSorting
  (JNIEnv *, jobject);

/*
 * Class:     main_MotorGrafico
 * Method:    hasFinished
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_main_MotorGrafico_hasFinished
  (JNIEnv *, jobject);

/*
 * Class:     main_MotorGrafico
 * Method:    getAlgorithmCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_main_MotorGrafico_getAlgorithmCount
  (JNIEnv *, jobject);

/*
 * Class:     main_MotorGrafico
 * Method:    getAlgorithmName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_main_MotorGrafico_getAlgorithmName
  (JNIEnv *, jobject, jint);

/*
 * Class:     main_MotorGrafico
 * Method:    getAlgorithmDescription
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_main_MotorGrafico_getAlgorithmDescription
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
